version: '3.7'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zahra
      POSTGRES_DB: ETL
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - airflow-net

  airflow-webserver:
    image: apache/airflow:2.7.1
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:zahra@postgres:5432/ETL
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: 'E3A9Nx5JsSP7iebXhKF3eyr2vRRdV_v-uMDjQD0JoFA='
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: bash -c "pip install apache-airflow[flask] && airflow db migrate && airflow webserver"
    volumes:
      - ./airflow:/opt/airflow
    networks:
      - airflow-net

  airflow-scheduler:
    image: apache/airflow:2.7.1
    command: bash -c "pip install apache-airflow[flask] && airflow db migrate && airflow scheduler"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:zahra@postgres:5432/ETL
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    depends_on:
      - postgres
    networks:
      - airflow-net

volumes:
  postgres-data:

networks:
  airflow-net:
    driver: bridge
